routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth.
// Authentication Routes.
$this->get('login', 'Auth\LoginController@showLoginForm')
    ->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')
    ->name('logout');

// Password Reset Routes.
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')
    ->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')
    ->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')
    ->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group(['middleware' => 'auth'], function () {
    // Logout
    Route::get('logout', 'Auth\LoginController@logout')
        ->name('.logout');

    // Home.
    Route::get('/', 'GeneralController@home')
        ->name('home');

    // Projects.
    Route::resource('project', 'ProjectController');

    // Add editor.
    Route::get('project/{project}/add-editor', 'ProjectController@getAddEditorPage')
        ->middleware('role:developer')
        ->name('project.add-editor.get');

    Route::post('project/{project}/add-editor', 'ProjectController@addEditor')
        ->middleware('role:developer')
        ->name('project.add-editor.post');

    // Translations.
    Route::resource('translation', 'TranslationController');

    // Translation file edit.
    Route::get('translation/{translation}/edit', [
        'as'         => 'translation.edit.file',
        'uses'       => 'TranslationController@editTranslationFile',
    ]);

    // Translation file edit.
    Route::patch('translation/{translation}/edit', [
        'as'         => 'translation.update.file',
        'uses'       => 'TranslationController@updateTranslationFile',
    ]);

    // Translation file download.
    Route::get('translation/{translation}/download', 'TranslationController@downloadTranslation')
        ->name('translation.download');

    // Translation progress.
    Route::get('translation/{translation}/progress', 'TranslationController@progress')
        ->name('translation.progress');

    // Translation progress.
    Route::get('translation/{translation}/completion-percentage', 'TranslationController@completionPercentage')
        ->name('translation.completion-percentage');
});

app/Models/Project.php
<?php

declare(strict_types = 1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Class Project
 * @package App\Models
 */
class Project extends Model
{
    /**
     * @var string
     */
    protected $table = 'projects';

    /**
     * @var array
     */
    protected $fillable = [
        'name',
    ];

    /**
     * @var array
     */
    protected $casts = [
        'name' => 'string',
    ];

    /**
     * @return BelongsToMany
     */
    public function users(): BelongsToMany
    {
        return $this->belongsToMany(User::class);
    }

    /**
     * @return HasMany
     */
    public function translations(): HasMany
    {
        return $this->hasMany(Translation::class);
    }

    /**
     * @return array
     */
    public function getUsersNamesAttribute(): array
    {
        $names = [];

        foreach ($this->users as $user) {
            $names[] = $user->name;
        }

        return $names;
    }
}

app/Models/Traits/DateHelper.php
<?php

declare(strict_types = 1);

namespace App\Models\Traits;

use Carbon\Carbon;

/**
 * Class DateHelper
 * @package App\Entities\Traits
 */
trait DateHelper
{
    /**
     * Get created at attribute.
     *
     * @param $value
     *
     * @return $this|\DateTime
     */
    public function getCreatedAtAttribute($value)
    {
        return $this->formatWithTimeZone($value);
    }

    /**
     * Get updated at attribute.
     *
     * @param $value
     *
     * @return $this|\DateTime
     */
    public function getUpdatedAtAttribute($value)
    {
        return $this->formatWithTimeZone($value);
    }

    /**
     * Convert to time zone.
     *
     * @param $date
     *
     * @return string
     */
    private function formatWithTimeZone($date)
    {
        $date = (new Carbon($date))->setTimezone(config('app.displayed_timezone'));

        return $date;
    }
}

app/Http/Controllers/ProjectController.php
<?php

declare(strict_types = 1);

namespace App\Http\Controllers;

use App\Http\Requests\Project\AddEditorRequest;
use App\Http\Requests\Project\StoreRequest;
use App\Http\Requests\Project\UpdateRequest;
use App\Models\Project;
use App\Models\User;
use App\Notifications\AccountCreated;
use App\Notifications\EditorAddedToProject;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Illuminate\View\View;

/**
 * Class ProjectController
 * @package App\Http\Controllers
 */
class ProjectController extends Controller
{
    /**
     * @param Request $request
     *
     * @return View
     */
    public function index(Request $request): View
    {
        $projectsQuery = Auth::user()->projects();

        if ($name = $request->query('name')) {
            $projectsQuery = $projectsQuery->where('name', 'like', "%{$name}%");
        }

        return view(
            'project.index',
            [
                'projects' => $projectsQuery
                    ->paginate(static::ITEMS_PER_PAGE)
            ]
        );
    }

    /**
     * @return View
     *
     * @throws AuthorizationException
     */
    public function create(): View
    {
        $this->authorize('create', Project::class);

        return view('project.create');
    }

    /**
     * @param StoreRequest $request
     *
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function store(StoreRequest $request): RedirectResponse
    {
        $this->authorize('create', Project::class);

        Auth::user()->projects()->create($request->all());

        return redirect(route('project.index'))
            ->with('success', trans('flash_messages.project.created'));
    }

    /**
     * @param Project $project
     *
     * @return View
     *
     * @throws AuthorizationException
     */
    public function edit(Project $project): View
    {
        $this->authorize('manipulate', $project);

        return view('project.edit', ['project' => $project]);
    }

    /**
     * @param UpdateRequest $request
     * @param Project $project
     *
     * @return RedirectResponse
     *
     * @throws AuthorizationException
     */
    public function update(UpdateRequest $request, Project $project): RedirectResponse
    {
        $this->authorize('manipulate', $project);

        $project->update($request->all());

        return redirect(route('project.index'))
            ->with('success', trans('flash_messages.project.updated'));
    }

    /**
     * @param Project $project
     *
     * @return JsonResponse
     *
     * @throws AuthorizationException
     * @throws \Exception
     */
    public function destroy(Project $project): JsonResponse
    {
        $this->authorize('manipulate', $project);

        $project->delete();

        Session::flash('success', trans('flash_messages.project.deleted'));

        return new JsonResponse(['redirect' => route('project.index')]);
    }

    /**
     * @param Project $project
     *
     * @return View
     * @throws AuthorizationException
     */
    public function getAddEditorPage(Project $project): View
    {
        $this->authorize('manipulate', $project);

        return view('project.add_editor', ['project' => $project]);
    }

    /**
     * @param AddEditorRequest $request
     * @param Project $project
     *
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function addEditor(AddEditorRequest $request, Project $project): RedirectResponse
    {
        $this->authorize('manipulate', $project);

        $flashMsg = trans('flash_messages.project.editor_added');

        /** @var User $user */
        $user = User::where('email', $request->get('email'))->first();

        // Create new user;
        if (!$user) {
            $emailParts = explode('@', $request->get('email'));
            $password = str_random(8);

            /** @var User $user */
            $user = User::create([
                'name'     => reset($emailParts),
                'email'    => $request->get('email'),
                'password' => $password,
            ]);

            $user->notify(new AccountCreated($password));

            $user->assignRole('editor');
        }

        if (!$project->users->contains($user)) {
            $project->users()->attach($user->getKey());
        } else {
            $flashMsg = trans('flash_messages.project.editor_already_exists');
        }

        $user->notify(new EditorAddedToProject($project));

        return redirect(route('project.index'))
            ->with('success', $flashMsg);
    }
}

resources/views/project/add_editor.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-flat col-md-9">
        <div class="panel-heading">
            <h5 class="panel-title">
                @lang('project.add_editor.title')
            </h5>
            <div class="heading-elements">
                <a href='{{ route('project.index') }}' class="btn btn-success">
                    <i class="icon icon-list"></i>
                    @lang('project.index.title')
                </a>
            </div>
        </div>
        <div class="panel-body">
            <form action="{{ route('project.add-editor.post', ['project' => $project]) }}" method="POST">
                {{ csrf_field() }}
                <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                    <label for="@lang('project.add_editor.labels.new')"></label>
                    <input type="email" class="form-control" name="email" placeholder="@lang('project.add_editor.labels.email')">
                    @if ($errors->has('email'))
                        <span class="help-block">
                            <strong>{{ $errors->first('email') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="text-right">
                    <button type="submit" class="btn btn-info">
                        @lang('common.add_editor')
                        <i class="icon-arrow-right14 position-right"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/project/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-flat col-md-9">
        <div class="panel-heading">
            <h5 class="panel-title">
                @lang('project.create.title')
            </h5>
            <div class="heading-elements">
                <a href='{{ route('project.index') }}' class="btn btn-success">
                    <i class="icon icon-list"></i>
                    @lang('project.index.title')
                </a>
            </div>
        </div>
        <div class="panel-body">
            <form action="{{ route('project.store') }}" method="POST">
                {{ csrf_field() }}
                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                    <label for="title">@lang('project.create.labels.name')</label>
                    <input type="text" class="form-control" name="name">
                    @if ($errors->has('name'))
                        <span class="help-block">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="text-right">
                    <button type="submit" class="btn btn-info">
                        @lang('common.submit')
                        <i class="icon-arrow-right14 position-right"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/project/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">
                @lang('project.create.title')
            </h5>
            <div class="heading-elements">
                <a href='{{ route('project.index') }}' class="btn btn-success">
                    <i class="icon icon-list"></i>
                    @lang('project.index.title')
                </a>
            </div>
        </div>
        <div class="panel-body">
            <form action="{{ route('project.update', ['project' => $project->id]) }}" method="POST">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="PATCH">
                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                    <label for="title">@lang('project.create.labels.name')</label>
                    <input type="text" class="form-control" name="name" value="{{ $project->name }}">
                    @if ($errors->has('name'))
                        <span class="help-block">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="text-right">
                    <button type="submit" class="btn btn-info">
                        @lang('common.submit')
                        <i class="icon-arrow-right14 position-right"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/project/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">
                @lang('project.index.title')
            </h5>
            @role('developer')
                <div class="heading-elements">
                    <a href='{{ route('project.create') }}' class="btn btn-success">
                        <i class="icon icon-plus2"></i>
                        @lang('project.index.create')
                    </a>
                </div>
            @endrole
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                @if($projects->count())
                    <form action="{{ route('project.index') }}">
                        <div class="form-group col-sm-3" style="padding-left: 0">
                            <div class="input-group">
                                <input type="text" name="name" class="form-control" placeholder="@lang('project.index.table.headers.name')" value="{{ Request::query('name') ?? '' }}">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit">@lang('common.search')</button>
                                    <a href='{{ route('project.index') }}' class="btn btn-info">@lang('common.clear')</a>
                                </span>
                            </div>
                        </div>
                    </form>
                    <table class="table">
                        <thead>
                        <tr class="bg-info">
                            <th>#</th>
                            <th>@lang('project.index.table.headers.name')</th>
                            <th>@lang('project.index.table.headers.translations_count')</th>
                            <th>@lang('project.index.table.headers.last_translation_at')</th>
                            <th>@lang('project.index.table.headers.created')</th>
                            <th>@lang('project.index.table.headers.translations')</th>
                            @role('developer')
                                <th>@lang('project.index.table.headers.members')</th>
                                <th>@lang('project.index.table.headers.create_translation')</th>
                                <th>@lang('project.index.table.headers.actions')</th>
                            @endrole
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($projects as $project)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>
                                    @role('developer')
                                        <a href="{{ route('project.edit', ['project' => $project->id]) }}">
                                            <strong>{{ $project->name }}</strong>
                                        </a>
                                    @endrole
                                    @role('editor')
                                        <strong>{{ $project->name }}</strong>
                                    @endrole
                                </td>
                                <td>{{ $project->translations->count() }}</td>
                                <td>
                                    @if($project->translations->count())
                                        {{ $project->translations->last()->created_at->format('d/m/Y H:i') }}
                                    @else
                                        ---
                                    @endif
                                </td>
                                <td>{{ $project->created_at->format('d/m/Y H:i') }}</td>
                                <td>
                                    <a href="{{ route('translation.index') }}?project={{ $project->id }}" class="btn border-slate text-teal-800 btn-flat">
                                        @lang('project.index.translations')
                                    </a>
                                </td>
                                @role('developer')
                                <td>
                                    @php $members = implode(', ', $project->users_names); @endphp
                                    <span data-popup="tooltip" title="" data-original-title="{{ $members }}">
                                        {{ str_limit($members, 10) }}
                                    </span>
                                </td>
                                <td>
                                    <a href="{{ route('translation.create') }}?project={{ $project->id }}" class="btn border-slate text-teal-800 btn-flat">
                                        @lang('project.index.create_translation')
                                    </a>
                                </td>
                                <td>
                                    <ul class="icons-list">
                                        <li class="dropdown dropdown">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                                <i class="icon-menu9"></i>
                                            </a>
                                            <ul class="dropdown-menu dropdown-menu-right">
                                                <li>
                                                    <a href="{{ route('project.add-editor.get', ['id' => $project->id]) }}">
                                                        <i class="icon icon-user-plus"></i>
                                                        @lang('common.add_editor')
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="{{ route('project.edit', ['id' => $project->id]) }}">
                                                        <i class="icon-pencil7"></i>
                                                        @lang('common.edit')
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="{{ route('project.destroy', ['id' => $project->id]) }}" class="confirmation-delete">
                                                        <i class="icon-trash"></i>
                                                        @lang('common.delete')
                                                    </a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </td>
                                @endrole
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                @else
                    <h4>@lang('project.index.no_projects')</h4>
                @endif
            </div>
        </div>
    </div>
    <div class="pagination text-center">{{ $projects->links() }}</div>
@endsection