routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth.
// Authentication Routes.
$this->get('login', 'Auth\LoginController@showLoginForm')
    ->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')
    ->name('logout');

// Password Reset Routes.
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')
    ->name('password.request');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')
    ->name('password.email');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')
    ->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group(['middleware' => 'auth'], function () {
    // Logout
    Route::get('logout', 'Auth\LoginController@logout')
        ->name('.logout');

    // Home.
    Route::get('/', 'GeneralController@home')
        ->name('home');

    // Projects.
    Route::resource('project', 'ProjectController');

    // Add editor.
    Route::get('project/{project}/add-editor', 'ProjectController@getAddEditorPage')
        ->middleware('role:developer')
        ->name('project.add-editor.get');

    Route::post('project/{project}/add-editor', 'ProjectController@addEditor')
        ->middleware('role:developer')
        ->name('project.add-editor.post');

    // Translations.
    Route::resource('translation', 'TranslationController');

    // Translation file edit.
    Route::get('translation/{translation}/edit', [
        'as'         => 'translation.edit.file',
        'uses'       => 'TranslationController@editTranslationFile',
    ]);

    // Translation file edit.
    Route::patch('translation/{translation}/edit', [
        'as'         => 'translation.update.file',
        'uses'       => 'TranslationController@updateTranslationFile',
    ]);

    // Translation file download.
    Route::get('translation/{translation}/download', 'TranslationController@downloadTranslation')
        ->name('translation.download');

    // Translation progress.
    Route::get('translation/{translation}/progress', 'TranslationController@progress')
        ->name('translation.progress');

    // Translation progress.
    Route::get('translation/{translation}/completion-percentage', 'TranslationController@completionPercentage')
        ->name('translation.completion-percentage');
});

app/Models/Traits/DateHelper.php
<?php

declare(strict_types = 1);

namespace App\Models\Traits;

use Carbon\Carbon;

/**
 * Class DateHelper
 * @package App\Entities\Traits
 */
trait DateHelper
{
    /**
     * Get created at attribute.
     *
     * @param $value
     *
     * @return $this|\DateTime
     */
    public function getCreatedAtAttribute($value)
    {
        return $this->formatWithTimeZone($value);
    }

    /**
     * Get updated at attribute.
     *
     * @param $value
     *
     * @return $this|\DateTime
     */
    public function getUpdatedAtAttribute($value)
    {
        return $this->formatWithTimeZone($value);
    }

    /**
     * Convert to time zone.
     *
     * @param $date
     *
     * @return string
     */
    private function formatWithTimeZone($date)
    {
        $date = (new Carbon($date))->setTimezone(config('app.displayed_timezone'));

        return $date;
    }
}

app/Models/Translation.php
<?php

declare(strict_types = 1);

namespace App\Models;

use App\Models\Traits\DateHelper;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;
use Spatie\MediaLibrary\Media;

/**
 * Class Translation
 * @package App\Models
 */
class Translation extends Model implements HasMediaConversions
{
    use HasMediaTrait, DateHelper;

    /**
     * @var string
     */
    protected $table = 'translations';

    /**
     * @var array
     */
    protected $fillable = [
        'project_id',
        'source_lang',
        'target_lang',
        'completion_progress',
    ];

    /**
     * @var array
     */
    protected $casts = [
        'project_id'            => 'number',
        'source_lang'           => 'string',
        'target_lang'           => 'string',
        'completion_progress'   => 'float',
    ];

    /**
     * @return BelongsTo
     */
    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }

    /**
     * @return float
     */
    public function getCompletionPercentageAttribute(): float
    {
        return round($this->getAttribute('completion_progress') * 100);
    }

    /**
     * @return Media
     */
    public function getSourceFileAttribute(): Media
    {
        return $this->getFirstMedia('translation.source');
    }

    /**
     * @return Media
     */
    public function getTargetFileAttribute(): Media
    {
        return $this->getFirstMedia('translation.target');
    }

    /**
     * @param Media|null $media
     */
    public function registerMediaConversions(Media $media = null)
    {

    }
}

app/Http/Controllers/TranslationController.php
<?php

declare(strict_types = 1);

namespace App\Http\Controllers;

use App\Http\Requests\Translation\StoreRequest;
use App\Jobs\TranslateLangFile;
use App\Models\Project;
use App\Models\Translation;
use Carbon\Carbon;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Session;
use Illuminate\View\View;
use PeterColes\Languages\LanguagesFacade;
use Spatie\MediaLibrary\Exceptions\FileCannotBeAdded;
use Spatie\MediaLibrary\Exceptions\InvalidConversion;
use Spatie\MediaLibrary\Media;
use Symfony\Component\HttpFoundation\BinaryFileResponse;

/**
 * Class TranslationController
 * @package App\Http\Controllers
 */
class TranslationController extends Controller
{
    /**
     * @param Request $request
     *
     * @return View
     */
    public function index(Request $request): View
    {
        $user = Auth::user();

        $translationsQuery = Translation::whereIn(
            'project_id', $user->projects()->pluck('id')
        )->latest();

        if ($projectId = $request->query('project')) {
            $translationsQuery = $translationsQuery->where('project_id', $projectId);
        }

        return view(
            'translation.index',
            [
                'projects'     => $user->projects,
                'translations' => $translationsQuery
                    ->paginate(static::ITEMS_PER_PAGE)
            ]
        );
    }

    /**
     * @return View
     *
     * @throws AuthorizationException
     */
    public function create(): View
    {
        $this->authorize('create', Translation::class);

        $availableLanguages = DB::table('google_supported_languages')
            ->pluck('language')
            ->toArray();
        $languages = LanguagesFacade::lookup($availableLanguages);

        return view(
            'translation.create',
            [
                'projects'  => Auth::user()->projects,
                'languages' => $languages
            ]
        );
    }

    /**
     * @param StoreRequest $request
     *
     * @return RedirectResponse
     *
     * @throws AuthorizationException
     *
     * @throws FileCannotBeAdded
     */
    public function store(StoreRequest $request): RedirectResponse
    {
        $this->authorize('create', Translation::class);

        /** @var Project $project */
        $project = Project::findOrFail($request->get('project_id'));

        $this->authorize('get', $project);

        /** @var Translation $translation */
        $translation = $project->translations()->create($request->all());

        // Translate.
        /** @var UploadedFile $sourceFile */
        $sourceFile = $request->file('file');
        $targetFilePath = sys_get_temp_dir().'/'.str_random(8);
        $copied = File::copy($sourceFile, $targetFilePath);

        $translation->addMedia($sourceFile)
            ->toMediaCollection('translation.source');

        if ($copied) {
            $targetTranslation = $translation
                ->addMediaFromUrl($targetFilePath)
                ->setName(
                    str_before(
                        $sourceFile->getClientOriginalName(),
                        '.'.$sourceFile->getClientOriginalExtension()
                    )
                )
                ->setFileName($sourceFile->getClientOriginalName())
                ->toMediaCollection('translation.target');
        }

        // Dispatch translation job.
        TranslateLangFile::dispatch($translation, $targetTranslation);

        return redirect(
            route(
                'translation.progress',
                [
                    'translation' => $translation->getKey(),
                ]
            )
        )->with('info', trans('flash_messages.translation.translating'));
    }

    /**
     * @param Translation $translation
     *
     * @return JsonResponse
     *
     * @throws AuthorizationException
     * @throws \Exception
     */
    public function destroy(Translation $translation): JsonResponse
    {
        $this->authorize('manipulate', $translation);

        $translation->clearMediaCollection('translation');
        $translation->delete();

        Session::flash('success', trans('flash_messages.translation.deleted'));

        return response()->json(['redirect' => route('translation.index')]);
    }

    /**
     * @param Translation $translation
     *
     * @return BinaryFileResponse
     *
     * @throws AuthorizationException
     */
    public function downloadTranslation(Translation $translation): BinaryFileResponse
    {
        $this->authorize('get', $translation);

        return response()->download($translation->target_file->getPath());
    }

    /**
     * @param Translation $translation
     *
     * @return View
     *
     * @throws AuthorizationException
     */
    public function editTranslationFile(Translation $translation): View
    {
        $this->authorize('get', $translation);

        $sourceTranslation = include $translation->source_file->getPath();
        $targetTranslation = include $translation->target_file->getPath();
        $sourceTranslationStrings = $targetTranslationStrings = [];

        array_walk_recursive(
            $sourceTranslation,
            function($value, $key) use (&$sourceTranslationStrings) {
                if (is_string($value)) {
                    $sourceTranslationStrings[] = $value;
                }
            }
        );

        array_walk_recursive(
            $targetTranslation,
            function($value, $key) use (&$targetTranslationStrings) {
                if (is_string($value)) {
                    $targetTranslationStrings[] = $value;
                }
            }
        );

        return view(
            'translation.edit',
            [
                'translation'              => $translation,
                'file'                     => $translation->target_file,
                'sourceTranslationStrings' => $sourceTranslationStrings,
                'targetTranslationStrings' => $targetTranslationStrings,
            ]
        );
    }

    /**
     * @param Request $request
     * @param Translation $translation
     *
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function updateTranslationFile(Request $request, Translation $translation): RedirectResponse
    {
        $this->authorize('get', $translation);

        $path = $translation->target_file->getPath();

        $fileContent = File::get($path);

        foreach ($request->get('strings') as $originalString =>  $updatedString) {
            $fileContent = str_replace($originalString, $updatedString, $fileContent);
        }

        File::put($path, $fileContent);

        $translation->updated_at = Carbon::now();
        $translation->save();

        return redirect(
            route(
                'translation.edit.file',
                ['translation' => $translation]
            ))
            ->with(
                'info',
                trans('flash_messages.translation.file.updated')
            );
    }

    /**
     * @param Translation $translation
     *
     * @return View
     *
     * @throws AuthorizationException
     */
    public function progress(Translation $translation): View
    {
        $this->authorize('manipulate', $translation);

        return view('translation.progress', ['translation' => $translation]);
    }

    /**
     * @param Translation $translation
     *
     * @return JsonResponse
     */
    public function completionPercentage(Translation $translation): JsonResponse
    {
        return response()->json(['percentage' => $translation->completion_percentage]);
    }
}

resources/views/translation/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-flat col-md-9">
        <div class="panel-heading">
            <h5 class="panel-title">
                @lang('translation.create.title')
            </h5>
            <div class="heading-elements">
                <a href='{{ route('translation.index') }}' class="btn btn-success">
                    <i class="icon icon-list"></i>
                    @lang('translation.index.title')
                </a>
            </div>
        </div>
        <div class="panel-body">
            <form action="{{ route('translation.store') }}" method="POST" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="form-group{{ $errors->has('project_id') ? ' has-error' : '' }}">
                    <label for="project_id">@lang('translation.create.labels.project')</label>
                    <select name="project_id" class="select2 form-control">
                        <option disabled selected>@lang('translation.create.labels.options.project')</option>
                        @foreach($projects as $project)
                            <option @if(Request::query('project') == $project->id || old('project_id') == $project->id) selected @endif value="{{ $project->id }}">{{ $project->name }}</option>
                        @endforeach
                    </select>
                    @if ($errors->has('project_id'))
                        <span class="help-block">
                            <strong>{{ $errors->first('project_id') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group{{ $errors->has('source_lang') ? ' has-error' : '' }}">
                    <label for="source_lang">@lang('translation.create.labels.source_lang')</label>
                    <select name="source_lang" class="select2 form-control">
                        <option disabled selected>@lang('translation.create.labels.options.source_lang')</option>
                        @foreach($languages as $key => $name)
                            <option @if(old('source_lang') === $key) selected @endif value="{{ $key }}">{{ $name }}</option>
                        @endforeach
                    </select>
                    @if ($errors->has('source_lang'))
                        <span class="help-block">
                            <strong>{{ $errors->first('source_lang') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group{{ $errors->has('target_lang') ? ' has-error' : '' }}">
                    <label for="target_lang">@lang('translation.create.labels.target_lang')</label>
                    <select name="target_lang" class="select2 form-control">
                        <option disabled selected>@lang('translation.create.labels.options.target_lang')</option>
                        @foreach($languages as $key => $name)
                            <option @if(old('target_lang') === $key) selected @endif value="{{ $key }}">{{ $name }}</option>
                        @endforeach
                    </select>
                    @if ($errors->has('target_lang'))
                        <span class="help-block">
                            <strong>{{ $errors->first('target_lang') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="form-group{{ $errors->has('file') ? ' has-error' : '' }}">
                    <label for="files">@lang('translation.create.labels.file')</label>
                    <input type="file" class="file-styled form-control" name="file" multiple>

                    @if($errors->has('file'))
                        <span class="help-block">
                            <strong>{{ $errors->first('file') }}</strong>
                        </span>
                    @endif
                </div>
                <div class="p-t-10 alert alert-danger no-border">
                    @lang('translation.create.labels.file_tips')
                </div>
                <div class="text-right">
                    <button type="submit" class="btn btn-info">
                        @lang('common.submit')
                        <i class="icon-arrow-right14 position-right"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/translation/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-flat col-md-9">
        <div class="panel-heading">
            <h5 class="panel-title">
                @lang('translation.edit.title', ['file' => $file->file_name, 'project' => $translation->project->name])
            </h5>
            <div class="heading-elements">
                <a href='{{ route('translation.index') }}' class="btn btn-success">
                    <i class="icon icon-list"></i>
                    @lang('translation.index.title')
                </a>
                <a href='{{ route('translation.download', ['translation' => $translation, 'media' => $file]) }}' class="btn btn-info">
                    <i class="icon icon-file-download2"></i>
                    @lang('translation.edit.download')
                </a>
            </div>
        </div>
        <div class="panel-body">
            <div class="alert alert-danger no-border">
                @lang('translation.edit.params_alert')
            </div>
            <form action="{{ route('translation.update.file', ['translation' => $translation, 'media' => $file]) }}" method="POST">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="PATCH">
                @foreach($targetTranslationStrings as $index => $string)
                    <div class="form-group">
                        @php
                            preg_match_all('/:[a-zA-Z0-9]+/', $sourceTranslationStrings[$index], $matches);
                            $label = $sourceTranslationStrings[$index];

                            foreach($matches[0] as $match) {
                                $label = str_replace($match, '<span class="label label-default">'.$match.'</span>', $label);
                            }
                        @endphp
                        <label for="">{!! $label !!}</label>
                        <input type="text" class="form-control" value="{{ $string }}" name="strings[{{ $string }}]" multiple>
                        @if($matches[0])
                            <label for="" class="help-block">
                                @lang('translation.edit.params_string', ['params' => implode(', ', $matches[0])])
                            </label>
                        @endif
                    </div>
                @endforeach
                <div class="text-right">
                    <button type="submit" class="btn btn-info">
                        @lang('common.submit')
                        <i class="icon-arrow-right14 position-right"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/translation/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">
                @lang('translation.index.title')
            </h5>
            @role('developer')
                <div class="heading-elements">
                    <a href='{{ route('translation.create') }}@if(Request::query('project'))?project={{ Request::query('project') }}@endif' class="btn btn-success">
                        <i class="icon icon-plus2"></i>
                        @lang('translation.index.create')
                    </a>
                </div>
            @endrole
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                @if($translations->count())
                    <form action="{{ route('translation.index') }}">
                        <div class="form-group col-sm-3" style="padding-left: 0">
                            <div class="input-group">
                                <select name="project" class="select2 form-control">
                                    <option disabled selected>@lang('translation.index.choose_project')</option>
                                    @foreach($projects as $project)
                                        <option @if(Request::query('project') == $project->id) selected @endif value="{{ $project->id }}">{{ $project->name }}</option>
                                    @endforeach
                                </select>
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit">@lang('common.search')</button>
                                    <a href='{{ route('project.index') }}' class="btn btn-info">@lang('common.clear')</a>
                                </span>
                            </div>
                        </div>
                    </form>
                    <table class="table">
                        <thead>
                        <tr class="bg-info">
                            <th>#</th>
                            <th>@lang('translation.index.table.headers.project_name')</th>
                            <th>@lang('translation.index.table.headers.files')</th>
                            <th>@lang('translation.index.table.headers.progress')</th>
                            <th>@lang('translation.index.table.headers.source_language')</th>
                            <th>@lang('translation.index.table.headers.target_language')</th>
                            <th>@lang('translation.index.table.headers.created')</th>
                            <th>@lang('translation.index.table.headers.updated')</th>
                            @role('developer')
                                <th>@lang('translation.index.table.headers.actions')</th>
                            @endrole
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($translations as $translation)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>
                                    <a href="{{ route('project.edit', ['project' => $translation->project->id]) }}">
                                        <strong>{{ $translation->project->name }}</strong>
                                    </a>
                                </td>
                                <td>
                                    <a href="{{ route('translation.edit.file', ['translation' => $translation->id]) }}" data-popup="tooltip" title="" data-original-title="@lang('common.edit')">
                                        <i class="icon icon-pencil7"></i>
                                    </a>
                                    <a href="{{ route('translation.download', ['translation' => $translation->id]) }}" data-popup="tooltip" title="" data-original-title="@lang('common.download')">
                                        <i class="icon  icon-file-download2"></i>
                                    </a>
                                    {{ $translation->target_file->file_name }}
                                    <br>
                                </td>
                                <td>
                                    <span class="label label-success">{{ $translation->completion_percentage }}%</span>
                                </td>
                                <td>
                                    <span class="label label-primary">
                                        {{ $translation->source_lang }}
                                    </span>
                                </td>
                                <td>
                                    <span class="label label-warning">
                                        {{ $translation->target_lang }}
                                    </span>
                                </td>
                                <td>{{ $translation->created_at->format('d/m/Y H:i') }}</td>
                                <td>{{ $translation->updated_at->format('d/m/Y H:i') }}</td>
                                @role('developer')
                                    <td>
                                        <ul class="icons-list">
                                            <li class="dropdown dropdown">
                                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                                    <i class="icon-menu9"></i>
                                                </a>
                                                <ul class="dropdown-menu dropdown-menu-right">
                                                    <li>
                                                        <a href="{{ route('translation.destroy', ['id' => $translation->id]) }}" class="confirmation-delete">
                                                            <i class="icon-trash"></i>
                                                            @lang('common.delete')
                                                        </a>
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </td>
                                @endrole
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                @else
                    <h4>@lang('translation.index.no_translations')</h4>
                @endif
            </div>
        </div>
    </div>
    <div class="pagination text-center">{{ $translations->links() }}</div>
@endsection

resources/views/translation/progress.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">
                @lang('translation.progress.title', ['project' => $translation->project->name])
            </h5>
            <div class="heading-elements">
                <a href='{{ route('translation.index') }}' class="btn btn-success">
                    <i class="icon icon-list"></i>
                    @lang('translation.index.title')
                </a>
            </div>
        </div>
        <div class="panel-body">
            <div class="content-group-sm">
                <p class="text-semibold">{{ $translation->target_file->file_name }}</p>
                <div class="progress">
                    <div id="transProgressBar" class="progress-bar bg-teal" data-tid="{{ $translation->id }}" data-completion-percentage="{{ $translation->completion_percentage }}" style="width: {{ $translation->completion_percentage }}%">
                        <span class="completion-percentage-text">{{ $translation->completion_percentage }}%</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('page_scripts')
    <script src="{{ asset('assets/js/translation.js') }}"></script>
@endsection